
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 29 21:05:05 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EndFor = 12;
  public static final int SquareBDer = 55;
  public static final int CurlyIzq = 56;
  public static final int Begin = 34;
  public static final int Coma = 46;
  public static final int PuntoComa = 44;
  public static final int TypeMatriz = 20;
  public static final int ParIzq = 52;
  public static final int Repeat = 14;
  public static final int TypeFloat = 17;
  public static final int ENTERO = 60;
  public static final int Of = 30;
  public static final int Default = 31;
  public static final int Numeral = 51;
  public static final int Else = 4;
  public static final int Arroba = 50;
  public static final int EndCase = 32;
  public static final int OP_DIV = 25;
  public static final int OP_LOGIC = 26;
  public static final int IDENTIFICADOR = 59;
  public static final int TypeList = 19;
  public static final int Then = 8;
  public static final int IN = 10;
  public static final int Punto = 45;
  public static final int While = 13;
  public static final int IF = 2;
  public static final int CurlyDer = 57;
  public static final int Ampersand = 48;
  public static final int For = 9;
  public static final int EndCall = 38;
  public static final int DECIMAL = 62;
  public static final int EOF = 0;
  public static final int DosPuntos = 43;
  public static final int RETURN = 39;
  public static final int ParDer = 53;
  public static final int error = 1;
  public static final int EndMain = 40;
  public static final int CADENA = 61;
  public static final int OP_MULT = 24;
  public static final int COMENTARIO = 63;
  public static final int SquareBIzq = 54;
  public static final int put = 41;
  public static final int ERROR = 64;
  public static final int ElseIf = 6;
  public static final int OP_RELA = 27;
  public static final int Case = 29;
  public static final int EndWhile = 15;
  public static final int special_characters = 58;
  public static final int TypeString = 18;
  public static final int Imp = 36;
  public static final int EndIf = 3;
  public static final int EndElse = 5;
  public static final int ImpLn = 35;
  public static final int get = 42;
  public static final int Call = 37;
  public static final int TBool = 22;
  public static final int OP_SUMA = 23;
  public static final int TypeInt = 16;
  public static final int TypeBool = 21;
  public static final int EndElseIf = 7;
  public static final int Apostrofe = 49;
  public static final int Main = 33;
  public static final int GuionBajo = 47;
  public static final int Range = 11;
  public static final int OP_ASIG = 28;
}

